# Generated by Django 4.1.7 on 2023-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teacher",
                    models.CharField(
                        choices=[
                            ("test", "test"),
                            ("test4", "test4"),
                            ("admin", "admin"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "assigned",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                            ("4A", "4A"),
                            ("4B", "4B"),
                            ("5A", "5A"),
                            ("5B", "5B"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
