# Generated by Django 4.1.7 on 2023-06-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("singup", "0002_teacherclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.CharField(
                        choices=[
                            ("test1", "test1"),
                            ("test3", "test3"),
                            ("test6", "test6"),
                            ("nanankal", "nanankal"),
                            ("ali", "ali"),
                            ("rakesh", "rakesh"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "assignclass",
                    models.CharField(
                        choices=[
                            ("1A", "1A"),
                            ("1B", "1B"),
                            ("2A", "2A"),
                            ("2B", "2B"),
                            ("3A", "3A"),
                            ("3B", "3B"),
                            ("4A", "4A"),
                            ("4B", "4B"),
                            ("5A", "5A"),
                            ("5B", "5B"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="teacherclass",
            name="teacher",
            field=models.CharField(
                choices=[
                    ("test", "test"),
                    ("test4", "test4"),
                    ("admin", "admin"),
                    ("admin1", "admin1"),
                    ("test7", "test7"),
                    ("tanguturi", "tanguturi"),
                ],
                max_length=100,
            ),
        ),
    ]
