# Generated by Django 4.1.7 on 2023-06-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singup", "0004_marks_alter_studentclass_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="marks", name="classes",),
    ]
